services:
  - type: web
    name: uurobot-strapi
    env: node
    region: frankfurt
    plan: free
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /_health
    autoDeploy: false
    envVars:
      - key: NODE_VERSION
        value: ~16.18.0
      - key: NODE_ENV
        value: production
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_KEY
        sync: false
      - key: CLOUDINARY_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: uurobot-strapi
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true

databases:
  - name: uurobot-strapi
    region: frankfurt
    plan: free